In [13]:
import numpy as np

vector = [10,40,35,42,56,67]
print(vector)
for pos, element in enumerate(vector):
    print(f"The element {element} is in the position {pos}")

matrix = [[11,24,35,44],[47,58,64,55],[73,82,99,66]]
for row in matrix: print(row)
print(range(len(matrix)))
row = len(matrix)
col = len(matrix[0])
for row_index in range(row):
    for col_index in range(col):
        print(f"the element {matrix[row_index][col_index]} is in the position {row_index},{col_index}")

[10, 40, 35, 42, 56, 67]
The element 10 is in the position 0
The element 40 is in the position 1
The element 35 is in the position 2
The element 42 is in the position 3
The element 56 is in the position 4
The element 67 is in the position 5
[11, 24, 35, 44]
[47, 58, 64, 55]
[73, 82, 99, 66]
range(0, 3)
the element 11 is in the position 0,0
the element 24 is in the position 0,1
the element 35 is in the position 0,2
the element 44 is in the position 0,3
the element 47 is in the position 1,0
the element 58 is in the position 1,1
the element 64 is in the position 1,2
the element 55 is in the position 1,3
the element 73 is in the position 2,0
the element 82 is in the position 2,1
the element 99 is in the position 2,2
the element 66 is in the position 2,3


In [66]:
import numpy as np

a = np.array([1,2,3]) # Creacion de vector, solo de tipos int, si se pone flotante se paroxima
print(a)
print(len(a)) #longitud de arreglo
print(a.shape) #dimensiones del vector/matriz
for i in a:
    print(i)
a[2] = 5 # Reasignacion de datos
print(a)

print("-------------------------------------------")
b = np.array([[1,2,3],[4,5,6]]) # Creacion matriz solo de tipos int
print(b)
rows, cols = b.shape # dimensiones de la matriz, la devuelve en forma de tupla
print(f"el numero de files de b es {rows} y el numero de columnas de b es {cols}")
print("-------------------------------------------")

z = np.zeros((2,2)) # crea una matriz de zeros de nxm
print(z)
print("-------------------------------------------")
o = np.ones((3,3)) # crea una matriz de unos de nxm
print(o)
print("-------------------------------------------")
e = np.eye(2) # crea una matriz diagonal de n
print(e)
print("-------------------------------------------")
r = np.random.randint(1,10,(2,2)) # crea una matriz de nxm de numeros enteros
print(r)
print("-------------------------------------------")
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]) # matriz de 4 filas y 4 columnas
d = c[0:3, 1:3] # slicing, no se incluye el valor superior, es decir
                # este parrafo toma las filas 0 a 2 (3-1) y las columnas 1 a 2 (3-1)
print(c)
print(d)
c[2,2] = 45 # reasignacion de valores, solo acepta enteros
print(c)
row1 = c[0,:] # cuando cortamos de esta manera devuelve un array o vector de 1 dimension
row1_1 = c[0:1,:] # devuelve una matriz de 1xn
print(row1)
print(row1_1)
col1 = c[:,0] # al igual que en las filas devuelve un vector
col1_1 = c[:,0:1] # devuelve una matriz de nx1
print(col1)
print(col1_1)
print("-------------------------------------------")
aa = np.array([[1,2],[3,4],[5,6]])
print(aa)
print(aa[[0,1,2],[0,1,0]]) # es como un tipo de zip, selecciona el valor de la matriz que se encuente
                           # en la posicion x,y, ejemplo, 0,0 - 1,0 - 2,0
print("-------------------------------------------")
bb = np.arange(1,11,3) # crea un vector en forma de rango, (inicio, final, paso)
print(bb)
cc = np.arange(4)
print(cc)
print("-------------------------------------------")
dd = aa[np.arange(3),[0,1,0]] # es la misma asignacion por posision pero con vectores diferentes
print(aa)
print(dd)
print("-------------------------------------------")
dd = c[np.arange(4), [0,2,1,3]] + 10 # esto devuelve los valores seleccionados en la lista
                                     # y ademas les suma 10
print(c)
print(dd)
c[np.arange(4), [0,2,1,3]] += 10 # modifica los valores que coincidan con las posiciones sumandoles 10
print(c)
print("-------------------------------------------")
matrix = np.array([4,7,8,1,0,3]) #tambien podemos buscar valores que cumplan una condicion
print(matrix)
print(matrix == 8)
print(matrix > 4)
print(matrix[matrix > 4]) #aqui retornamos esos valores unicamente en forma de vector
print("-------------------------------------------")
matrix1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix1)
print(matrix1 > 4)
print(matrix1[matrix1 > 4])
print("-------------------------------------------")
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]]) # las operaciones de suma y resta son elemento a elemento
m2 = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(m1)
print(m2)
m3 = m1+m2
m4 = m1-m2
m5 = m1[::-1,::-1] # con esta sintaxis volteamos un arreglo vertical [::-1,_] y horizontal [_,::-1]
m6 = m5-m2
print(m5)
print(m3)
print(m4)
print(m6)
print("-------------------------------------------")
multiply1 = np.array([[1,2],
                      [3,4]]) #Para multiplicar matrices debe cumplirse que  el # de columnas
multiply2 = np.array([[5,6],
                     [7,8]]) # de A debe ser igual al numero de filas de B
result = multiply1 * multiply2 # las dimensiones del resultado es el # de filas de A x el # de columnas de B
print(result) # [(1*5)+(2*7)=19 (1*6)+(2*8)=22 (3*5)+(4*7)=43 (3*6)+(4*8)=50]
              # para este caso la multiplicacion es como las otras operaciones, elemento por elemento
division = multiply1 / multiply2
print(division)
square1 = multiply1 * multiply1
square2 = np.square(multiply1)
print(square1)
print(square2)
print("-------------------------------------------")
dot1 = multiply1.dot(multiply2) # con la funcion dot si se hace la multiplicacion matricial
dot2 = np.dot(multiply1,multiply2)
print(dot1)
print(dot2)
v = np.array([1,2])
w = np.array([10,11])
dot3 = v.dot(w) # Cuando se multiplican dos vectores arroja la sumatoria de la multiplicacion
                # deben tener la misma longitud o dimensiones
print(dot3)
dot4 = multiply1.dot(v) # Cuando se multiplica una matrix por un arreglo, el resultado es una sumatoria de
                        # la multiplicacion de los elementos en cada sub arreglo
print(dot4) # [(1*1)+(2*2)=5 (3*1)+(4*2)=11], tienen que tener dimensiones correctas
sum1 = np.sum(multiply1) # esto calcula la sumatoria de todos los valores de la matrix
print(sum1)
sum_columns = np.sum(multiply1, axis=0) # devuelve la sumatoria de las columnas
print(sum_columns)
sum_rows = np.sum(multiply1, axis=1) # devuelve la sumatoria de las filas
print(sum_rows)
print("-------------------------------------------")
x = np.array([[1,2],[3,4]])
print(x)
print(x.T) # imprime la trasnpuesta de la matrix, es decir filas por columnas y viceversa
print("-------------------------------------------")
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x) # crea un arreglo vacio con las dimensiones de x, np.zeros(x.shape)

for i in range(len(x)):
    y[i,:] = x[i,:] + v # la fila i con todas sus columnas es igual a la fila x con sus columnas
                        # mas la suma elemento a elemento con v
vv = np.tile(v,(4,1)) # crea copias de un elemento
print(vv)
print(y)
print(x+v)
print(x+vv)
print("-------------------------------------------")
x = np.array([1,2,3]) # no se pueden multiplicar porque este vector es (1,3)
w = np.array([4,5]) # este es (1,2)
print(x)
print(w)
x_re = np.reshape(x,(3,1)) # se convierte a (3,1) y ahora (3,1) * (1,2)
print(x_re)
print(x_re*w) # filas por columnas
y = np.array([[1,2,3],[4,5,6]]) # como tienen dimensiones compatibles se pueden sumar
print(y+x)
# para sumar y con w debemos transponer y para que las dimensiones sean compatibles
y_trans = y.T
print(y_trans)
print(y_trans+w)
w_re = np.reshape(w,(2,1))
print(w_re)
print(y+w_re)
print(y*2) # multiplica los elementos de la matriz por una constante
print("-------------------------------------------")
x = np.array([0,1,2,3,4,5,6,7,8,9])
print(x[1:7:2]) # devuelve los elementos del 1 al 6 en saltos de 2
print(x[-2:10]) # imprime los elementos desde el penultimo hasta el ultimo
print(x[-3:3:-1]) # imprime los elementos desde el antepenultimo hasta el numero 3 hascia atras (-1)
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
rows = np.array([[0,0],
                [3,3]])
columns = np.array([[0,2],
                   [0,2]])
rows2 = np.array([0,0,3,3])
columns2 = np.array([0,2,0,2])
print(x[rows, columns]) #aqui los elementos se obtienen en forma de matrix
print(x[rows2, columns2]) #Aqui los elementos se obtienen en forma de vector 
print(x.sum(1)) # devuelve la suma de las filas si el axis es 1 o dolumnas si el axis es 0
y = np.array([[0,1],
              [1,1],
              [2,2]])
rowsums = y.sum(1)
less2 = y < 2
print(less2)
print(y[less2])
print("-----------------------------------------")
print(rowsums <= 2) #reurn [true, true, false]
print(y[:,np.array([True, False])])# se deben tener en cuenta las dimensiones en las operaciones
                                   # ya que puden afectar de gran manera el resultado, en este caso
                                   # dependiendo de cuales dimensiones tenga la lista de busqueda
                                   # imprime filas o colunas
rows = (x.sum(1) % 2) == 0
print(rows)
columns = [0,2]
print(x[rows,columns]) # en este caso como solo 2 valores son true, se puede colcar un columns
                       # con una dimension diferente a este que encaje con el numero de trues
print("-----------------------------------------")
print(x.ndim) # imprime las dimensiones, filas y columnas = 2 dimensiones
print(x.size) # imprime el numero de elementos
g = np.linspace(0,5,10) # crea un arreglo de vayan desde el 0 al 5 separados por 10 numeros
print(g)
f = x.flatten() # convierte una matriz en un vector
print(f)
temp = x[:2, ::2] # toma los valores desde la fila 0 hasta la 1 y las columnas a pasos de a 2 (1,3)
print(temp)
print(x.max())
print(x.min())
print(x.max(0))
print(x.min(1))
print(x.cumsum(axis=1))
a = np.array([0, np.pi/2, np.pi, np.pi*1.5])
sine_a = np.sin(a)
print(sine_a)
b = np.array([[1, 4, 2],
             [3, 4, 6],
             [0, -1, 5]])
print(b)
sort_b = np.sort(b,axis=None)
print(sort_b)
sort_row_b = np.sort(b,1)
print(sort_row_b)
sort_function_b = np.sort(b,axis=0,kind='mergesort')
print(sort_function_b)
val_list = [('Daniel', 1997, 22.5),('Camilo',2000,18.5)]
dtypes = [('name','S10'),('grad_year', int),('years',float)]
# los datatypes ofrecen muchos mas tipos de datos que los que python tiene por defecto
# algunos de estos son int, int8, int16, int32, int64 que pueden ser representados por letras
# i1,i2,i3,i4, igual ocurre con el float, ademas ofrece booleanos, unsigned int, complex, strings, etc
# Para el caso de los string podemos determinas cuantas letras tendra cada elemento del arreglo
# si le pasamos el datatype S1 = 1 letra, S20 = 20 letras.
arr = np.array(val_list,dtypes)
print(arr)
sort_arr = np.sort(arr, order='name')
print(sort_arr)
sort_arr2 = np.sort(arr,order=['grad_year','years'])
print(sort_arr2)
nan_array = np.array([np.nan,1,2,np.nan,3,4,5])
print(nan_array[~np.isnan(nan_array)])
print(b[1:]) # si solo se corta con un solo de esta fila, hasta el final de la matix)
print(b[...,1]) # imprime solo la columna 1
print(b[1,...]) # imprime solo la fila 1
print(b[:,1]) # lo mismo que arriba
print(b[1,:])
print(b[:,1:])
c = np.arange(0,60,5)
c = c.reshape(3,4)
print(c)
for i in np.nditer(c):
    print(i)
d = c.copy()
#for i in d.flatten():
#    i[...] = 2*i
for i in np.nditer(c, op_flags = ['readwrite']):
    i[...] = 2*i
print(c)
print(d)
print(c.itemsize) # determina el numero de bits del arreglo segun el tipo (int=8, float=32)
print(np.empty([3,2], dtype = int)) # crea un array rando segun el tipo de datos
s = b'Hello Worldd' # lo convierte en bits
bufferarray = np.frombuffer(s, dtype = 'S1')
print(bufferarray)
bufferarray2 = np.frombuffer(s, dtype = 'S2')
print(bufferarray2)
a = np.array([1,2,3,4])
b = np.array ([5,6,7,8])
print(a)
c = np.append(a, b) # la funcion devuelve un nuevo arreglo pero asignada a una nuvera variales
print(c)
matrix2 = np.array([[1,2,3],[4,5,6]])
d = np.append(matrix2, np.array([[10],[100]]), axis=1) # para añadir al final una columna 
print(d)
e = np.append(d, np.array([[0,0,0,0]]),axis=0) # para añadir al final una fila
                                               # el metodo hstack agrega horizontal y el metodo vstack vertical
print(e)
aa = np.insert(a,2,7)
print(aa) # se agrega en el indece deseado
ab = np.delete(aa,2) # para borrar un elemento en el indice indicado
print(ab)
ac = np.delete(matrix2,0,axis=0)
ad = np.delete(matrix2,0,axis=1)
print(ac)
print(ad)
indexa = np.where(a == 2) # devuelve el indice
print(indexa[0])
indexb = np.where(matrix2 == 4) # devuelve el indice
print(f"{indexb[0]},{indexb[1]}")
addition = lambda val: val+2
ba = addition(a) # otra forma de modificar los elementos de un arreglo pero deben cambiar de variable
                 # no puede usarse con listas
print(ba)
for i in np.nditer(a, op_flags = ['readwrite']):
    i[...] = i + 2
print(a) # este metodo modifica el vlaor de la varibale
list1 = a.tolist()
print(list1)
array1 = np.array([400,800,200,700,1000,2000,300])
xmax = array1.max()
xmin = array1.min()
array_norm = (array1 - xmin) / (xmax - xmin)
print(array_norm) # para normalizar los valores entre un valor y otro
normalized = lambda val: (val - val.min()) / (val.max() - val.min()) 
print(normalized(array1))
print("------------------------------------------------")
load_array = np.loadtxt('np_array.txt', dtype=int)
print(load_array) # podemos convertir un archivo de texto a un array
load_array2 = np.loadtxt('np_array2.txt', skiprows=1)
print(load_array2) # podemos saltarnos los encabezados
x, y, z = np.loadtxt('np_array2.txt',skiprows=1,unpack=True)
print(x, y, z) # con el unpack cada columna se asigna a una variable
load_array3 = np.genfromtxt('np_array3.txt', skip_header=1, filling_values=0, dtype=float)
print(load_array3) # este metodo se utiliza cuando puede haber un valor erroneo
x2 = np.arange(0.0,5.0,1.0)
np.savetxt('test_np.out',x2,delimiter=',',fmt='%.2f') # guarda un array
load_array_float = load_array.astype(float) # cambia el tipo de dato
print(load_array_float)
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[1,2,3],[4,5,6]])
print(np.array_equal(a1,a2)) # comparamos dos arreglos
a3 = np.array_split(a1,2) # partimos un arreglo al indice pasado
print(a3)
print(a1[1,2])
print(a1[1][2])
l = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12],
              [13, 14, 15, 16]])
l_slicing = l[:,[0,1,2,0]] # aqui imprime todas las files de estas columnas
                           # y repite la 0
print(l)
print(l_slicing)
l_slicing2 = l[[1,2,3,0]][:,[3,2,1,0]] # en vez de cada elemento multiplicarse directamente
                                       # se multiplica el 1 por cada valor de columnas y se imprime en una fila
                                       # y asi sucesivamente como (1,2,3,0)*(3,2,1,0)
print(l_slicing2)
print("------------------------------------------------")
r1 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8]])
print(np.resize(x,(4,4))) # con este metodo agrandamos el arreglo con numeros random
#print(r_r1)
r1.resize((4,4)) # con este otro metodo llenamos los nuevos campos de ceros
print(r1)
r2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8]])
print(r2)
r3 = r2.reshape((4,2)) # con el nmetodo resize podemos agrandar el arreglo sin importar las dimensiones
                  # ya que se agregan nuevos numeros o elementos, pero en el metodo reshape, solo se
                  # puede modificar las dimensiones del arreglo a unas dimensiones que no modiifquen 
                  # el numero total de valores, como por ejemplo a 4,2 
print(r3)
print(r3.flatten()) # convertimos a un arreglo
n1 = np.array([1,2,3,4])
n2 = np.append(n1,[7,8,9,10])
print(n2) # axis 0 igual filas, axis 1 = oolumnas
y1 = np.array([1,2,3,4])
y2 = np.array([5.,6.,7.,8.])    
y3 = np.concatenate((y1,y2)) # une los arreglos
print(y3)
y4 = np.array([[10,20,30,40],
               [50,60,70,80]])
y5 = np.vstack((y1,y4)) # para agregar filas
print(y5)
y6 = np.array([[10],
               [20],
               [30]])
y7 = np.hstack((y5,y6)) # para agregar columnas
print(y7)
yy = np.array([[1,2,3,4,1,2,3,4],
              [1,2,3,4,5,6,7,8]])
y8 = np.split(yy,1,0)
y9 = np.split(yy,2,0)
y10 = np.split(yy,1,1)
y11 = np.split(yy,2,1)# este metodo hace split pero segun el indice
print(y8)
print(y9)
print(y10)
print(y11)
y12 = np.hsplit(yy,4)
y13 = np.vsplit(yy,2) 
print(y12)
print(y13)
print(np.diag(l,0)) # extrae los valores de la diagonal, podemos modifica la diagonal a extraer
                    # 0 es la diagonal principal +0 o -0 son diferentes diagonales
print(np.diagonal(l))
print(np.fliplr(l)) # voltea la matrix de izquierda a derecha
print(np.flipud(l)) # voltea la matrix de abajo a arriba
row_index, col_index = np.where(l < 6)
print(row_index)
print(col_index)
print(l[[row_index],[col_index]])
l_diag = np.diag(l)
print(np.where(l == l_diag)) # tambien podemos localizar varios puntos
np.fill_diagonal(l,[10,20,30,40])
print(l)
print("Calculando las diagonales y restandolas")
print("Metodo convencional:")
lista = [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]
dim = len(lista)
diag1 = 0
diag2 = 0
for idx in range(dim):
        diag1 += lista[idx][idx]
        diag2 += lista[dim-1-idx][dim-1-idx]
result = diag1 - diag2
print(diag1)
print(diag2)
print(result)
print("Metodo Numpy:")
lista = np.array([[ 1,  2,  3,  4],
                  [ 5,  6,  7,  8],
                  [ 9, 10, 11, 12],
                  [13, 14, 15, 16]])
diag1 = np.sum(np.diag(lista))
diag2 = np.sum(np.diag(lista[:,::-1]))
result = diag1 - diag2
print(l[:,::-1])
print(diag1)
print(diag2)
print(result)

[1 2 3]
3
(3,)
1
2
3
[1 2 5]
-------------------------------------------
[[1 2 3]
 [4 5 6]]
el numero de files de b es 2 y el numero de columnas de b es 3
-------------------------------------------
[[0. 0.]
 [0. 0.]]
-------------------------------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-------------------------------------------
[[1. 0.]
 [0. 1.]]
-------------------------------------------
[[7 6]
 [8 3]]
-------------------------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 45 12]
 [13 14 15 16]]
[1 2 3 4]
[[1 2 3 4]]
[ 1  5  9 13]
[[ 1]
 [ 5]
 [ 9]
 [13]]
-------------------------------------------
[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
-------------------------------------------
[ 1  4  7 10]
[0 1 2 3]
-------------------------------------------
[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
-------------------------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 45 12]
 [13 14 15 16]]
[11